const fs = require("fs");
const dir = "public/data/examenes";

// Catalan → Spanish dictionary (long entries first)
const dict = [
  // Longest specific card texts
  ["Particionament d'un disc amb esquema MBR.", "Particionado de un disco con esquema MBR."],
  ["cinc particions de 2 GB cadascuna. Durant el procés, indiqueu quin tipus de particions heu utilitzat (primàries, estesa o lògiques) i expliqueu breument per què ha estat necessari utilitzar aquests tipus de partició.", "cinco particiones de 2 GB cada una. Durante el proceso, indicad qué tipo de particiones habéis utilizado (primarias, extendida o lógicas) y explicad brevemente por qué ha sido necesario utilizar estos tipos de partición."],
  ["A continuació, descriviu les limitacions principals del sistema de particionament MBR. Finalment, utilitzeu la comanda lsblk per identificar el disc i totes les particions creades, mostrant la seva mida i estructura.", "A continuación, describid las limitaciones principales del sistema de particionado MBR. Finalmente, utilizad el comando lsblk para identificar el disco y todas las particiones creadas, mostrando su tamaño y estructura."],
  ["Utilitzant el segon disc de 10 GB, creeu una taula de particions", "Utilizando el segundo disco de 10 GB, cread una tabla de particiones"],
  ["l'esquema GPT amb l'eina gdisk. Genereu cinc particions de 2 GB cadascuna dins del disc.", "el esquema GPT con la herramienta gdisk. Generad cinco particiones de 2 GB cada una dentro del disco."],
  ["Modificació de particions amb eina gràfica GParted.", "Modificación de particiones con herramienta gráfica GParted."],
  ["Identifiqueu les dues últimes particions creades dins d'aquest disc.", "Identificad las dos últimas particiones creadas dentro de este disco."],
  ["Realitzeu una operació que permeti fusionar aquestes dues particions en una sola, de manera que s'unifiqui l'espai disponible. Descriviu el procediment seguit dins de l'aplicació i indiqueu quina és la mida final de la nova partició resultant.", "Realizad una operación que permita fusionar estas dos particiones en una sola, de manera que se unifique el espacio disponible. Describid el procedimiento seguido dentro de la aplicación e indicad cuál es el tamaño final de la nueva partición resultante."],
  ["Format, muntatge i configuració de particions.", "Formateo, montaje y configuración de particiones."],
  ["Formateu la primera partició amb el sistema de fitxers ext4. Creeu el directori /mnt/ioc/ext4 i munteu-hi la partició amb permisos de lectura i escriptura. Verifiqueu que el muntatge és correcte.", "Formatead la primera partición con el sistema de archivos ext4. Cread el directorio /mnt/ioc/ext4 y montad la partición con permisos de lectura y escritura. Verificad que el montaje es correcto."],
  ["Formateu la segona partició amb el sistema de fitxers NTFS. Creeu el directori /mnt/ioc/ntfs i munteu-hi la partició en mode només lectura.", "Formatead la segunda partición con el sistema de archivos NTFS. Cread el directorio /mnt/ioc/ntfs y montad la partición en modo solo lectura."],
  ["Configureu la tercera partició com a àrea d'intercanvi (swap) del sistema. Activeu-la i configureu-la perquè tingui prioritat respecte a altres possibles àrees de swap.", "Configurad la tercera partición como área de intercambio (swap) del sistema. Activadla y configuradla para que tenga prioridad respecto a otras posibles áreas de swap."],
  ["Configureu el sistema perquè la partició muntada a l'apartat 4a es munti automàticament durant l'arrencada del sistema.", "Configurad el sistema para que la partición montada en el apartado 4a se monte automáticamente durante el arranque del sistema."],
  ["Creació d'un volum lògic amb LVM.", "Creación de un volumen lógico con LVM."],
  ["Afegiu dos discs virtuals nous de 2 GB cadascun. Utilitzant LVM, convertiu-los en volums físics, creeu un grup de volums", "Añadid dos discos virtuales nuevos de 2 GB cada uno. Utilizando LVM, convertidlos en volúmenes físicos, cread un grupo de volúmenes"],
  ["A partir d'aquest grup, creeu un volum lògic de 4 GB", "A partir de este grupo, cread un volumen lógico de 4 GB"],
  ["Instal·lació de programari i localització d'executables.", "Instalación de software y localización de ejecutables."],
  ["Instal·leu l'editor de text gedit", "Instalad el editor de texto gedit"],
  ["Utilitzeu una comanda adequada per localitzar l'executable del programa", "Utilizad un comando adecuado para localizar el ejecutable del programa"],
  ["Indiqueu si esperàveu trobar l'executable en aquesta ubicació", "Indicad si esperabais encontrar el ejecutable en esta ubicación"],
  ["Configureu un sistema de còpia de seguretat programada", "Configurad un sistema de copia de seguridad programada"],
  ["Expliqueu quina eina heu seleccionat i per què és adequada", "Explicad qué herramienta habéis seleccionado y por qué es adecuada"],
  ["Configureu la còpia perquè s'executi automàticament segons una planificació definida", "Configurad la copia para que se ejecute automáticamente según una planificación definida"],
  ["Creeu els grups biblioteca i treballador.", "Cread los grupos biblioteca y trabajador."],
  ["Creeu un usuari nou amb el vostre primer cognom", "Cread un usuario nuevo con vuestro primer apellido"],
  ["biblioteca com a grup principal i treballador com a grup secundari", "biblioteca como grupo principal y trabajador como grupo secundario"],
  ["Configureu el sistema perquè les contrasenyes tinguin una longitud mínima de 8 caràcters", "Configurad el sistema para que las contraseñas tengan una longitud mínima de 8 caracteres"],
  ["Configureu la xarxa de la màquina amb Ubuntu usant Netplan", "Configurad la red de la máquina con Ubuntu usando Netplan"],
  ["Definiu una configuració amb connectivitat a la xarxa", "Definid una configuración con conectividad a la red"],
  ["Instal·leu el servidor vsftpd. Un cop instal·lat, inicieu el servei i verifiqueu", "Instalad el servidor vsftpd. Una vez instalado, iniciad el servicio y verificad"],
  ["Connecteu-vos per FTP des de la màquina física", "Conectaos por FTP desde la máquina física"],
  ["Instal·leu Wireshark a la màquina amb Ubuntu. Inicieu una captura", "Instalad Wireshark en la máquina con Ubuntu. Iniciad una captura"],
  ["Accediu al fitxer /var/log/syslog", "Acceded al archivo /var/log/syslog"],
  ["localitzeu les entrades relacionades amb el reinici del servei FTP", "localizad las entradas relacionadas con el reinicio del servicio FTP"],
  ["Configureu les contrasenyes dels usuaris amb requisits de complexitat.", "Configurad las contraseñas de los usuarios con requisitos de complejidad."],
  ["Configureu polítiques de seguretat locals", "Configurad políticas de seguridad locales"],
  ["Creeu un usuari nou a la màquina amb Windows 11. Assigneu-li una contrasenya i comproveu que compleix els requisits de seguretat", "Cread un usuario nuevo en la máquina con Windows 11. Asignadle una contraseña y comprobad que cumple los requisitos de seguridad"],
  ["Obriu el Windows Event Viewer i localitzeu l'esdeveniment registrat", "Abrid el Windows Event Viewer y localizad el evento registrado"],
  ["Configuració de la xarxa amb Ubuntu usant la comanda ip", "Configuración de la red con Ubuntu usando el comando ip"],
  ["Instal·leu el paquet nmap des dels repositoris oficials.", "Instalad el paquete nmap desde los repositorios oficiales."],
  ["Executeu una exploració bàsica sobre la vostra pròpia màquina", "Ejecutad una exploración básica sobre vuestra propia máquina"],
  ["Identifiqueu els ports oberts, filtrats i tancats.", "Identificad los puertos abiertos, filtrados y cerrados."],
  ["Identifiqueu quin servei correspon a cada port detectat.", "Identificad qué servicio corresponde a cada puerto detectado."],
  ["Instal·leu i inicieu el servei vsftpd si no està actiu.", "Instalad e iniciad el servicio vsftpd si no está activo."],
  ["Connecteu-vos via FTP a la vostra pròpia màquina", "Conectaos via FTP a vuestra propia máquina"],
  ["Determineu l'adreça MAC de la vostra màquina física.", "Determinad la dirección MAC de vuestra máquina física."],
  ["Determineu l'adreça MAC de la màquina virtual Ubuntu.", "Determinad la dirección MAC de la máquina virtual Ubuntu."],
  ["Identifiqueu l'adreça MAC del router o porta d'enllaç predeterminada.", "Identificad la dirección MAC del router o puerta de enlace predeterminada."],
  ["Consulteu la correspondència IP–MAC mitjançant la comanda arp.", "Consultad la correspondencia IP-MAC mediante el comando arp."],
  ["Forceu una comunicació amb el router i actualitzeu la taula ARP.", "Forzad una comunicación con el router y actualizad la tabla ARP."],
  ["Expliqueu la diferència entre ARP dinàmic i ARP estàtic.", "Explicad la diferencia entre ARP dinámico y ARP estático."],
  ["Indiqueu quins riscos de seguretat estan associats a l'ARP spoofing.", "Indicad qué riesgos de seguridad están asociados al ARP spoofing."],
  ["Instal·leu WinServer i configureu-lo com a controlador de domini", "Instalad WinServer y configuradlo como controlador de dominio"],
  ["Verifiqueu que durant la promoció del servidor s'ha creat automàticament la zona directa del domini.", "Verificad que durante la promoción del servidor se ha creado automáticamente la zona directa del dominio."],
  ["Creeu la zona inversa corresponent a la xarxa del servidor.", "Cread la zona inversa correspondiente a la red del servidor."],
  ["Utilitzeu l'assistent gràfic per crear un registre A.", "Utilizad el asistente gráfico para crear un registro A."],
  ["Creeu un registre CNAME anomenat www que actuï com a àlies del controlador de domini.", "Cread un registro CNAME llamado www que actúe como alias del controlador de dominio."],
  ["Creeu dos grups de seguretat anomenats bibliotecari i usuari.", "Cread dos grupos de seguridad llamados bibliotecario y usuario."],
  ["Creeu dos comptes d'usuari anomenats Martí i Jana.", "Cread dos cuentas de usuario llamadas Martí y Jana."],
  ["Afegiu Martí al grup bibliotecari i Jana al grup usuari.", "Añadid Martí al grupo bibliotecario y Jana al grupo usuario."],
  ["Creeu un fitxer de text que contingui la data actual.", "Cread un archivo de texto que contenga la fecha actual."],
  ["Configureu els permisos del fitxer", "Configurad los permisos del archivo"],
  ["Configureu la xarxa perquè la màquina tingui una IP compatible", "Configurad la red para que la máquina tenga una IP compatible"],
  ["Uniu la màquina al domini eac3.t\u00e9u_ioc_user.home", "Unid la máquina al dominio eac3.t\u00e9u_ioc_user.home"],
  ["Creeu una carpeta anomenada documentacio al servidor.", "Cread una carpeta llamada documentacion en el servidor."],
  ["Compartiu-la a través del protocol SMB.", "Compartidla a través del protocolo SMB."],
  ["Instal·leu el paquet samba.", "Instalad el paquete samba."],
  ["Creeu una carpeta anomenada imatges", "Cread una carpeta llamada imagenes"],
  ["Creeu una carpeta anomenada documents", "Cread una carpeta llamada documentos"],
  ["Creeu el grup bibliotecari al sistema si és necessari.", "Cread el grupo bibliotecario en el sistema si es necesario."],
  ["Compartiu una impressora. Podeu usar una impressora real", "Compartid una impresora. Podéis usar una impresora real"],
  ["Instal·leu els paquets necessaris de Samba i dependències.", "Instalad los paquetes necesarios de Samba y dependencias."],
  ["Configureu una IP estàtica a la màquina servidor.", "Configurad una IP estática en la máquina servidor."],
  ["Provisioneu el domini amb samba-tool", "Aprovisionad el dominio con samba-tool"],
  ["Configureu el servei DNS integrat de Samba.", "Configurad el servicio DNS integrado de Samba."],
  ["Inicieu el servei i verifiqueu el funcionament", "Iniciad el servicio y verificad el funcionamiento"],
  ["Instal·leu un client de correu electrònic d'escriptori", "Instalad un cliente de correo electrónico de escritorio"],
  ["Configureu un compte de correu real", "Configurad una cuenta de correo real"],
  ["Envieu un correu de prova a un altre compte.", "Enviad un correo de prueba a otra cuenta."],
  ["Verifiqueu la recepció correcta del missatge.", "Verificad la recepción correcta del mensaje."],
  ["Instal·leu el servidor OpenSSH a Ubuntu.", "Instalad el servidor OpenSSH en Ubuntu."],
  ["Verifiqueu que el servei està actiu i escoltant al port 22.", "Verificad que el servicio está activo y escuchando en el puerto 22."],
  ["Instal·leu un client SSH a la màquina física", "Instalad un cliente SSH en la máquina física"],
  ["Connecteu-vos remotament a la màquina Ubuntu", "Conectaos remotamente a la máquina Ubuntu"],
  ["Executeu comandes administratives bàsiques remotament.", "Ejecutad comandos administrativos básicos remotamente."],
  ["Desactiveu l'accés SSH de l'usuari root", "Desactivad el acceso SSH del usuario root"],
  ["Compileu-lo manualment amb gcc", "Compiladlo manualmente con gcc"],
  ["Creeu una pàgina de manual per al programa", "Cread una página de manual para el programa"],
  ["Visualitzeu-lo amb groff abans d'instal·lar-lo.", "Visualizadlo con groff antes de instaladlo."],
  ["Instal·leu-lo comprimit a /usr/share/man/man3/", "Instaladlo comprimido en /usr/share/man/man3/"],
  ["Actualitzeu la base de dades de manuals", "Actualizad la base de datos de manuales"],
  ["Comproveu que es pot consultar correctament amb la comanda man.", "Comprobad que se puede consultar correctamente con el comando man."],
  ["Instal·leu Git a Ubuntu.", "Instalad Git en Ubuntu."],
  ["Configureu nom d'usuari i correu electrònic globals.", "Configurad nombre de usuario y correo electrónico globales."],
  ["Creeu un repositori local amb un nom lliure.", "Cread un repositorio local con un nombre libre."],
  ["Realitzeu almenys dos commits", "Realizad al menos dos commits"],
  ["Realitzeu un clon (clone) del repositori des d'una altra màquina.", "Realizad un clon (clone) del repositorio desde otra máquina."],
  
  // Shorter word replacements
  ["l'usuari", "el usuario"],
  ["l'equip", "el equipo"],
  ["l'empresa", "la empresa"],
  ["l'exercici", "el ejercicio"],
  ["l'enunciat", "el enunciado"],
  ["l'arrencada", "el arranque"],
  ["l'eina", "la herramienta"],
  ["l'esquema", "el esquema"],
  ["l'enllaç", "el enlace"],
  ["l'extendida", "la extendida"],
  ["l'apartat", "el apartado"],
  ["l'opció", "la opción"],
  ["l'estructura", "la estructura"],
  ["l'objectiu", "el objetivo"],
  ["l'accés", "el acceso"],
  ["l'espai", "el espacio"],
  ["d'un", "de un"],
  ["d'una", "de una"],
  ["d'una", "de una"],
  ["d'instal·lar", "de instalar"],
  ["d'arrencada", "de arranque"],
  ["d'usuari", "de usuario"],
  ["d'anàlisi", "de análisis"],
  ["d'actualitzar", "de actualizar"],
  ["d'aquestes", "de estas"],
  ["d'aquesta", "de esta"],
  ["d'aquest", "de este"],
  ["d'executables", "de ejecutables"],
  ["d'intercanvi", "de intercambio"],
  ["d'Active Directory", "de Active Directory"],
  ["d'Ubuntu", "de Ubuntu"],
  ["d'impremta", "de imprenta"],

  // Catalan verbs (imperative)
  ["Identifiqueu", "Identificad"],
  ["identifiqueu", "identificad"],
  ["Expliqueu", "Explicad"],
  ["expliqueu", "explicad"],
  ["Expliqueu", "Explicad"],
  ["Utilitzeu", "Utilizad"],
  ["utilitzeu", "utilizad"],
  ["utilitzant", "utilizando"],
  ["utilitzar", "utilizar"],
  ["Configureu", "Configurad"],
  ["configureu", "configurad"],
  ["Verifiqueu", "Verificad"],
  ["verifiqueu", "verificad"],
  ["Indiqueu", "Indicad"],
  ["indiqueu", "indicad"],
  ["Descriviu", "Describid"],
  ["descriviu", "describid"],
  ["Determineu", "Determinad"],
  ["determineu", "determinad"],
  ["Forceu", "Forzad"],
  ["forceu", "forzad"],
  ["Mostreu", "Mostrad"],
  ["mostreu", "mostrad"],
  ["Actualitzeu", "Actualizad"],
  ["actualitzeu", "actualizad"],
  ["Genereu", "Generad"],
  ["genereu", "generad"],
  ["Formateu", "Formatead"],
  ["formateu", "formatead"],
  ["Munteu", "Montad"],
  ["munteu", "montad"],
  ["munteu-la", "montadla"],
  ["munteu-hi", "montadla"],
  ["Activeu-la", "Activadla"],
  ["Instal·leu", "Instalad"],
  ["instal·leu", "instalad"],
  ["Afegiu", "Añadid"],
  ["Creeu", "Cread"],
  ["creeu", "cread"],
  ["Obriu", "Abrid"],
  ["obriu", "abrid"],
  ["Accediu", "Acceded"],
  ["accediu", "acceded"],
  ["Localitzeu", "Localizad"],
  ["localitzeu", "localizad"],
  ["Responeu", "Responded"],
  ["Compraveu", "Comprobad"],
  ["comproveu", "comprobad"],
  ["Assigneu", "Asignad"],
  ["assigneu", "asignad"],
  ["Executeu", "Ejecutad"],
  ["executeu", "ejecutad"],
  ["executeu-lo", "ejecutadlo"],
  ["Consulteu", "Consultad"],
  ["Compartiu", "Compartid"],
  ["compartiu-la", "compartidla"],
  ["Compareu", "Comparad"],
  ["Justifiqueu", "Justificad"],
  ["Feu", "Haced"],
  ["Observeu", "Observad"],
  ["Reflexioneu", "Reflexionad"],
  ["justifiqueu", "justificad"],
  ["Incloeu", "Incluid"],
  ["Convertiu", "Convertid"],
  ["convertiu-los", "convertidlos"],
  ["Retalleu", "Recortad"],
  ["Diferencieu", "Diferenciad"],
  ["Repetiu", "Repetid"],
  ["Descarregueu", "Descargad"],
  ["descarregueu", "descargad"],
  ["Reviseu", "Revisad"],
  ["reviseu", "revisad"],
  ["Comproveu", "Comprobad"],
  ["Compileu", "Compilad"],
  ["compileu-lo", "compiladlo"],
  ["Visualitzeu", "Visualizad"],
  ["visualitzeu-lo", "visualizadlo"],
  ["Inicieu", "Iniciad"],
  ["inicieu", "iniciad"],
  ["Analitzeu", "Analizad"],
  ["Connecteu-vos", "Conectaos"],
  ["Definiu", "Definid"],
  ["Envieu", "Enviad"],
  ["Verifiqueu", "Verificad"],
  ["Avalueu", "Evaluad"],
  ["Especifiqueu", "Especificad"],
  
  // Noun endings -ció → -ción
  ["instal·lació", "instalación"],
  ["Instal·lació", "Instalación"],
  ["configuració", "configuración"],
  ["Configuració", "Configuración"],
  ["verificació", "verificación"],
  ["Verificació", "Verificación"],
  ["creació", "creación"],
  ["Creació", "Creación"],
  ["modificació", "modificación"],
  ["Modificació", "Modificación"],
  ["gestió", "gestión"],
  ["Gestió", "Gestión"],
  ["promoció", "promoción"],
  ["Promoció", "Promoción"],
  ["compartició", "compartición"],
  ["Compartició", "Compartición"],
  ["compilació", "compilación"],
  ["Compilació", "Compilación"],
  ["anàlisi", "análisis"],
  ["Anàlisi", "Análisis"],
  ["integració", "integración"],
  ["Integració", "Integración"],
  ["administració", "administración"],
  ["Administració", "Administración"],
  ["actualització", "actualización"],
  ["Actualització", "Actualización"],
  ["introducció", "introducción"],
  ["avaluació", "evaluación"],
  ["Avaluació", "Evaluación"],
  ["prevenció", "prevención"],
  ["recuperació", "recuperación"],
  ["informació", "información"],
  ["Informació", "Información"],
  ["interconnexió", "interconexión"],
  ["solució", "solución"],
  ["presentació", "presentación"],
  ["Presentació", "Presentación"],
  ["comprovació", "comprobación"],
  ["diferència", "diferencia"],
  ["diferències", "diferencias"],
  ["funció", "función"],
  ["definició", "definición"],
  ["edició", "edición"],
  
  // -tat → -dad
  ["seguretat", "seguridad"],
  ["Seguretat", "Seguridad"],
  ["disponibilitat", "disponibilidad"],
  ["estabilitat", "estabilidad"],
  ["prioritat", "prioridad"],
  ["unitat", "unidad"],
  ["complexitat", "complejidad"],
  ["velocitat", "velocidad"],
  ["capacitat", "capacidad"],
  ["activitat", "actividad"],
  ["necessitat", "necesidad"],
  ["possibilitat", "posibilidad"],
  ["finalitat", "finalidad"],
  ["qualitat", "calidad"],

  // Common Catalan words
  ["partició", "partición"],
  ["particions", "particiones"],
  ["particionat", "particionado"],
  ["particionament", "particionado"],
  ["taula de particions", "tabla de particiones"],
  ["eina", "herramienta"],
  ["fitxer", "archivo"],
  ["fitxers", "archivos"],
  ["contrasenya", "contraseña"],
  ["contrasenyes", "contraseñas"],
  ["connexió", "conexión"],
  ["connexions", "conexiones"],
  ["connectivitat", "conectividad"],
  ["xarxa", "red"],
  ["Xarxa", "Red"],
  ["programari", "software"],
  ["domini", "dominio"],
  ["paquets", "paquetes"],
  ["servei", "servicio"],
  ["serveis", "servicios"],
  ["repositori", "repositorio"],
  ["repositoris", "repositorios"],
  ["nucli", "núcleo"],
  ["memòria virtual", "memoria virtual"],
  ["Memòria", "Memoria"],
  ["multitasca", "multitarea"],
  ["controladors", "controladores"],
  ["contenidors virtuals", "contenedores virtuales"],
  ["contenidor", "contenedor"],
  ["bibliotecari", "bibliotecario"],
  ["treballador", "trabajador"],
  ["imatge", "imagen"],
  ["imatges", "imágenes"],
  ["elements", "elementos"],
  ["connectors", "conectores"],
  ["externs", "externos"],
  ["virtuals", "virtuales"],
  ["discs", "discos"],
  ["usant", "usando"],
  ["Assigna", "Asigna"],
  ["assigna", "asigna"],
  ["proporcionat", "proporcionado"],
  ["proporcionats", "proporcionados"],
  ["equips", "equipos"],
  ["equip", "equipo"],
  ["dispositius", "dispositivos"],
  ["dispositiu", "dispositivo"],
  ["ordinador", "ordenador"],
  ["segon", "segundo"],
  ["després", "después"],
  ["diverses", "diversas"],
  ["diversos", "diversos"],
  ["noves", "nuevas"],
  ["nous", "nuevos"],
  ["molta", "mucha"],
  ["només", "solo"],
  ["cadascun", "cada uno"],
  ["cadascuna", "cada una"],
  ["tots dos", "ambos"],
  ["correcte", "correcto"],
  ["correcta", "correcta"],
  ["correctes", "correctas"],
  ["funcionament", "funcionamiento"],
  ["rendiment", "rendimiento"],
  ["respecte", "respecto"],

  // Catalan connectors
  ["però", "pero"],
  ["també", "también"],
  ["perquè", "para que"],
  ["per què", "por qué"],
  ["què", "qué"],
  ["Què", "Qué"],
  ["quins", "qué"],
  ["quines", "qué"],
  ["Quins", "Qué"],
  ["Quines", "Qué"],
  ["aquest", "este"],
  ["aquesta", "esta"],
  ["aquests", "estos"],
  ["aquestes", "estas"],
  ["altre", "otro"],
  ["altra", "otra"],
  ["altres", "otros"],
  ["mateix", "mismo"],
  ["mateixa", "misma"],
  ["mateixos", "mismos"],
  ["mateixes", "mismas"],
  ["vostre", "vuestro"],
  ["vostra", "vuestra"],
  ["vostre", "vuestro"],
  ["com a", "como"],
  ["hi ha", "hay"],
  ["dins", "dentro"],
  ["més", "más"],
  
  // Catalan accent fixes
  ["està", "está"],
  ["estàtica", "estática"],
  ["màscara", "máscara"],
  ["gràfica", "gráfica"],
  ["gràfic", "gráfico"],
  ["màquina", "máquina"],
  ["Màquina", "Máquina"],
  ["tècnic", "técnico"],
  ["tècnics", "técnicos"],
  ["tècniques", "técnicas"],
  ["automàticament", "automáticamente"],
  ["automàtic", "automático"],
  ["automàtica", "automática"],
  ["simultàniament", "simultáneamente"],
  ["electrònic", "electrónico"],
  ["freqüència", "frecuencia"],
  ["distàncies", "distancias"],
  ["ergonòmics", "ergonómicos"],
  ["dinàmic", "dinámico"],
  ["dinàmics", "dinámicos"],
  ["àlies", "alias"],
  ["paràmetre", "parámetro"],
  ["bàsica", "básica"],
  ["bàsiques", "básicas"],
  ["còpia", "copia"],
  ["trànsit", "tránsito"],
  ["transferència", "transferencia"],
  ["informàtic", "informático"],
  ["informàtics", "informáticos"],
  ["mecànic", "mecánico"],
  ["caràcters", "caracteres"],
  ["circumstàncies", "circunstancias"],
  ["correspondència", "correspondencia"],
  ["Observacions", "Observaciones"],
  ["observacions", "observaciones"],

  // Single word connectors  
  [" ", " "],
  
  // The "i" (and) → "y"
  [" y y ", " y "],
  [", i ", ", y "],
  [". i ", ". y "],
  ["; i ", "; y "],
  [" i ", " y "],
  ["\ni ", "\ny "],
];

// Sort by length DESC
dict.sort((a, b) => b[0].length - a[0].length);

let total = 0;
const files = fs.readdirSync(dir).filter(f => f.endsWith(".json"));

files.forEach(f => {
  let c = fs.readFileSync(dir + "/" + f, "utf8");
  dict.forEach(([cat, es]) => {
    if (c.includes(cat)) {
      const parts = c.split(cat);
      total += parts.length - 1;
      c = parts.join(es);
    }
  });
  fs.writeFileSync(dir + "/" + f, c);
});

console.log(`Total: ${total} reemplazos`);
