import json

with open('public/data/preguntas-directas/pd-all.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_ids = {c['id'] for c in data['cards']}

card1_front = (
    "(DWEC — Examen 1\u00aa eval / Arrays) Escribe un script que:\n\n"
    "1. Solicite datos de **3 personas** (nombre, apellido, fecha nacimiento, tel\u00e9fono)\n"
    "   mediante `prompt()` y almacene en **arrays separados**.\n\n"
    "2. **Normalice** los datos guard\u00e1ndolos en min\u00fasculas.\n\n"
    "3. **Valide** antes de almacenar:\n"
    "   - Tel\u00e9fono: empiece con 6, 7 o 9 y tenga **9 d\u00edgitos exactos**\n"
    "   - Fecha: formato **dd-mm-aaaa**\n\n"
    "4. Si falla la validaci\u00f3n, muestre aviso y **no almacene**.\n\n"
    "5. Funci\u00f3n `imprimePersonasOrdenadas()`: imprime en consola los nombres\n"
    "   ordenados alfab\u00e9ticamente con primera letra may\u00fascula.\n"
    "   Formato: `[Nombre]`"
)

card1_back = (
    "```javascript\n"
    "// Arrays para almacenar\n"
    "const nombres = [];\n"
    "const apellidos = [];\n"
    "const fechasNac = [];\n"
    "const telefonos = [];\n"
    "\n"
    "// Solicitar datos de 3 personas\n"
    "for (let i = 0; i < 3; i++) {\n"
    "  let nombre = prompt(\"Nombre persona \" + (i + 1) + \":\");\n"
    "  let apellido = prompt(\"Apellido persona \" + (i + 1) + \":\");\n"
    "  let fecha = prompt(\"Fecha nacimiento (dd-mm-aaaa) persona \" + (i + 1) + \":\");\n"
    "  let tlf = prompt(\"Tel\u00e9fono persona \" + (i + 1) + \":\");\n"
    "\n"
    "  // Validar tel\u00e9fono: 9 d\u00edgitos y empieza con 6, 7 o 9\n"
    "  const tlfValido = /^[679]\\d{8}$/.test(tlf);\n"
    "  // Validar fecha: formato dd-mm-aaaa\n"
    "  const fechaValida = /^\\d{2}-\\d{2}-\\d{4}$/.test(fecha);\n"
    "\n"
    "  if (!tlfValido) {\n"
    "    alert(\"Tel\u00e9fono inv\u00e1lido. Debe tener 9 d\u00edgitos y empezar por 6, 7 o 9.\");\n"
    "  }\n"
    "  if (!fechaValida) {\n"
    "    alert(\"Fecha inv\u00e1lida. Debe tener formato dd-mm-aaaa.\");\n"
    "  }\n"
    "\n"
    "  // Solo almacenar si ambas validaciones pasan\n"
    "  if (tlfValido && fechaValida) {\n"
    "    nombres.push(nombre.toLowerCase());\n"
    "    apellidos.push(apellido.toLowerCase());\n"
    "    fechasNac.push(fecha);\n"
    "    telefonos.push(tlf);\n"
    "  }\n"
    "}\n"
    "\n"
    "// Funci\u00f3n que imprime ordenado\n"
    "function imprimePersonasOrdenadas() {\n"
    "  const ordenados = [...nombres].sort();\n"
    "  ordenados.forEach(n => {\n"
    "    const capitalizada = n.charAt(0).toUpperCase() + n.slice(1);\n"
    "    console.log(\"[\" + capitalizada + \"]\");\n"
    "  });\n"
    "}\n"
    "\n"
    "imprimePersonasOrdenadas();\n"
    "```"
)

card2_front = (
    "(DWEC — Examen 1\u00aa eval / Clases) Crea en JavaScript:\n\n"
    "1. Clase **Persona** con propiedades privadas `nombre`, `apellido`, `fechaNacimiento`.\n"
    "   - Getters: `getNombre()`, `getApellido()`, `getNacimiento()`\n"
    "   - Setters: `setNombre()`, `setApellido()`, `setNacimiento()`\n"
    "     que **no acepten datos vac\u00edos**.\n\n"
    "2. Clase **PersonaCivil** que **herede** de Persona y a\u00f1ada:\n"
    "   - Propiedades `dni`, `telefono`\n"
    "   - Getters/setters correspondientes\n"
    "   - M\u00e9todo `imprimirDatos()` que saque:\n"
    "     `[nombre][apellido][fechaNacimiento][DNI][tel\u00e9fono]`\n\n"
    "3. Crea **3 instancias** de PersonaCivil e imprime sus datos."
)

card2_back = (
    "```javascript\n"
    "class Persona {\n"
    "  #nombre;\n"
    "  #apellido;\n"
    "  #fechaNacimiento;\n"
    "\n"
    "  constructor(nombre, apellido, fechaNacimiento) {\n"
    "    this.#nombre = nombre;\n"
    "    this.#apellido = apellido;\n"
    "    this.#fechaNacimiento = fechaNacimiento;\n"
    "  }\n"
    "\n"
    "  getNombre() { return this.#nombre; }\n"
    "  getApellido() { return this.#apellido; }\n"
    "  getNacimiento() { return this.#fechaNacimiento; }\n"
    "\n"
    "  setNombre(n) { if (n.trim() !== \"\") this.#nombre = n; }\n"
    "  setApellido(a) { if (a.trim() !== \"\") this.#apellido = a; }\n"
    "  setNacimiento(f) { if (f.trim() !== \"\") this.#fechaNacimiento = f; }\n"
    "}\n"
    "\n"
    "class PersonaCivil extends Persona {\n"
    "  #dni;\n"
    "  #telefono;\n"
    "\n"
    "  constructor(nombre, apellido, fechaNacimiento, dni, telefono) {\n"
    "    super(nombre, apellido, fechaNacimiento);\n"
    "    this.#dni = dni;\n"
    "    this.#telefono = telefono;\n"
    "  }\n"
    "\n"
    "  getDNI() { return this.#dni; }\n"
    "  getTelefono() { return this.#telefono; }\n"
    "  setDNI(d) { if (d.trim() !== \"\") this.#dni = d; }\n"
    "  setTelefono(t) { if (t.trim() !== \"\") this.#telefono = t; }\n"
    "\n"
    "  imprimirDatos() {\n"
    "    console.log(\"[\" + this.getNombre() + \"][\" + this.getApellido()\n"
    "      + \"][\" + this.getNacimiento() + \"][\" + this.#dni\n"
    "      + \"][\" + this.#telefono + \"]\");\n"
    "  }\n"
    "}\n"
    "\n"
    "// Crear 3 instancias\n"
    "const p1 = new PersonaCivil(\"ana\", \"l\u00f3pez\", \"15-03-2000\", \"12345678Z\", \"612345678\");\n"
    "const p2 = new PersonaCivil(\"luis\", \"garc\u00eda\", \"22-07-1999\", \"87654321X\", \"722334455\");\n"
    "const p3 = new PersonaCivil(\"carla\", \"mart\u00ednez\", \"10-11-2001\", \"45678901B\", \"998877665\");\n"
    "\n"
    "p1.imprimirDatos();\n"
    "p2.imprimirDatos();\n"
    "p3.imprimirDatos();\n"
    "```"
)

card3_front = (
    "(DWEC — Examen 1\u00aa eval / Formulario) Dado un formulario HTML con los campos:\n"
    "Nombre*, 1er Apellido*, 2\u00ba Apellido, Fecha nacimiento, DNI, Email*, Contrase\u00f1a*, Repetir contrase\u00f1a*\n\n"
    "Implementa las siguientes validaciones:\n"
    "1. **May\u00fasculas autom\u00e1ticas** en Nombre, 1er Apellido, 2\u00ba Apellido al escribir\n"
    "2. **Fecha** (dd/mm/aaaa) con regex y edad > 16 a\u00f1os al salir del campo\n"
    "3. **DNI**: 8 d\u00edgitos + letra (regex) al salir del campo\n"
    "4. **Email**: alfanum\u00e9rico + . - antes @, dominio de 2-3 letras\n"
    "5. **Contrase\u00f1as**: coinciden, \u2265 8 chars, min 1 may\u00fascula, 1 min\u00fascula, 1 d\u00edgito al salir del repetir\n"
    "6. **Campos obligatorios** (*) al pulsar Enviar"
)

card3_back = (
    "**validacion.js completo:**\n\n"
    "```javascript\n"
    "// 1. May\u00fasculas autom\u00e1ticas al escribir\n"
    "document.getElementById(\"nombre\").addEventListener(\"input\", function() {\n"
    "  this.value = this.value.toUpperCase();\n"
    "});\n"
    "document.getElementById(\"apellido1\").addEventListener(\"input\", function() {\n"
    "  this.value = this.value.toUpperCase();\n"
    "});\n"
    "document.getElementById(\"apellido2\").addEventListener(\"input\", function() {\n"
    "  this.value = this.value.toUpperCase();\n"
    "});\n"
    "\n"
    "// 2. Validar fecha (dd/mm/aaaa) y edad > 16 al salir del campo\n"
    "document.getElementById(\"fechaNac\").addEventListener(\"blur\", function() {\n"
    "  const val = this.value.trim();\n"
    "  const regex = /^\\d{2}\\/\\d{2}\\/\\d{4}$/;\n"
    "  if (!regex.test(val)) {\n"
    "    alert(\"Formato fecha inv\u00e1lido. Use dd/mm/aaaa.\");\n"
    "    return;\n"
    "  }\n"
    "  const [dia, mes, anyo] = val.split(\"/\").map(Number);\n"
    "  const nacimiento = new Date(anyo, mes - 1, dia);\n"
    "  const hoy = new Date();\n"
    "  let edad = hoy.getFullYear() - nacimiento.getFullYear();\n"
    "  const m = hoy.getMonth() - nacimiento.getMonth();\n"
    "  if (m < 0 || (m === 0 && hoy.getDate() < nacimiento.getDate())) {\n"
    "    edad--;\n"
    "  }\n"
    "  if (edad <= 16) {\n"
    "    alert(\"Debe ser mayor de 16 a\u00f1os.\");\n"
    "  }\n"
    "});\n"
    "\n"
    "// 3. Validar DNI (8 d\u00edgitos + letra) al salir\n"
    "document.getElementById(\"dni\").addEventListener(\"blur\", function() {\n"
    "  const regex = /^\\d{8}[A-Za-z]$/;\n"
    "  if (!regex.test(this.value.trim())) {\n"
    "    alert(\"DNI inv\u00e1lido. Debe tener 8 d\u00edgitos y una letra.\");\n"
    "  }\n"
    "});\n"
    "\n"
    "// 4. Validar email al salir\n"
    "document.getElementById(\"email\").addEventListener(\"blur\", function() {\n"
    "  const regex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9]+\\.[a-zA-Z]{2,3}$/;\n"
    "  if (!regex.test(this.value.trim())) {\n"
    "    alert(\"Email inv\u00e1lido.\");\n"
    "  }\n"
    "});\n"
    "\n"
    "// 5. Validar contrase\u00f1as al salir de repetir\n"
    "document.getElementById(\"pass2\").addEventListener(\"blur\", function() {\n"
    "  const p1 = document.getElementById(\"pass1\").value;\n"
    "  const p2 = this.value;\n"
    "  if (p1 !== p2) {\n"
    "    alert(\"Las contrase\u00f1as no coinciden.\");\n"
    "    return;\n"
    "  }\n"
    "  if (p1.length < 8) {\n"
    "    alert(\"La contrase\u00f1a debe tener al menos 8 caracteres.\");\n"
    "    return;\n"
    "  }\n"
    "  if (!/[A-Z]/.test(p1)) {\n"
    "    alert(\"Debe contener al menos una may\u00fascula.\");\n"
    "    return;\n"
    "  }\n"
    "  if (!/[a-z]/.test(p1)) {\n"
    "    alert(\"Debe contener al menos una min\u00fascula.\");\n"
    "    return;\n"
    "  }\n"
    "  if (!/\\d/.test(p1)) {\n"
    "    alert(\"Debe contener al menos un d\u00edgito.\");\n"
    "  }\n"
    "});\n"
    "\n"
    "// 6. Campos obligatorios al enviar\n"
    "document.getElementById(\"formRegistro\").addEventListener(\"submit\", function(e) {\n"
    "  e.preventDefault();\n"
    "  const obligatorios = [\n"
    "    { id: \"nombre\", label: \"Nombre\" },\n"
    "    { id: \"apellido1\", label: \"Primer Apellido\" },\n"
    "    { id: \"email\", label: \"Email\" },\n"
    "    { id: \"pass1\", label: \"Contrase\u00f1a\" },\n"
    "    { id: \"pass2\", label: \"Repetir Contrase\u00f1a\" }\n"
    "  ];\n"
    "  let vacios = obligatorios.filter(c =>\n"
    "    document.getElementById(c.id).value.trim() === \"\"\n"
    "  ).map(c => c.label);\n"
    "  if (vacios.length > 0) {\n"
    "    alert(\"Campos obligatorios vac\u00edos: \" + vacios.join(\", \"));\n"
    "  }\n"
    "});\n"
    "```"
)

new_cards = [
    {"id": "pd-dwec-013", "front": card1_front, "back": card1_back, "tags": ["dwec", "examen", "arrays", "validacion", "1eval"], "difficulty": "hard"},
    {"id": "pd-dwec-014", "front": card2_front, "back": card2_back, "tags": ["dwec", "examen", "clases", "herencia", "1eval"], "difficulty": "hard"},
    {"id": "pd-dwec-015", "front": card3_front, "back": card3_back, "tags": ["dwec", "examen", "formulario", "validacion", "1eval"], "difficulty": "hard"},
]

for nc in new_cards:
    if nc['id'] not in existing_ids:
        data['cards'].append(nc)
        print(f"Added: {nc['id']}")
    else:
        print(f"Already exists: {nc['id']}")

with open('public/data/preguntas-directas/pd-all.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nTotal cards now: {len(data['cards'])}")
